# Generated by Django 6.0.3 on 2026-05-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='handle',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
