# Generated by Django 6.0.3 on 2026-06-01 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_socialmedia_handle_socialmedia_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_company_per_user'),
        ),
    ]
